meta:
  engine: 4.1.0
units:
  # Proxy Spacing Variables
  kx: 19 
  ky: 19
  px: 19.5
  py: 19.5
  case_px: kx+4
  case_py: ky+4 
  cpx: case_px
  cpy: case_py
points:
  zones:
    matrix:
      anchor:
        shift: [175,-175]
      key:
        padding: 1ky
        spread: 1kx
      columns:
        pinky:
          rows.thumb.skip: true
          key:
            stagger: 0
            column_net: P2
        ring:
          rows.thumb.skip: true
          key:
            stagger: 5
            column_net: P3
        middle:
          rows.thumb.skip: true
          key:
            stagger: 3
            column_net: P4
        index:
          key:
            stagger: -8
            column_net: P5
        inner:
          key:
            stagger: -2
            column_net: P6
      rows:
        thumb:
          row_net: P10
        bottom:
          row_net: P16
        home:
          row_net: P14
        top:
          row_net: P15
outlines:
  case_raw:
    - what: rectangle
      where: true
      size: [cpx,cpy]
      fillet: 0.8
  raw:
    - what: rectangle
      where: true
      size: [px,py]
      fillet: 0.8
  case_compensation:
    - what: polygon
      operation: stack
      points:
        - ref: matrix_inner_thumb
          shift: [0.5cpx,-0.5cpy]
        - ref: matrix_pinky_bottom
          shift: [-0.5cpx,-1.5cpy+2]
        - ref: matrix_pinky_home
          shift: [-0.5cpx,0]
        - ref: matrix_inner_home
          shift: [0.5cpx,0] 
      fillet: 0.8
  compensation:
    - what: polygon
      operation: stack
      points:
        - ref: matrix_inner_thumb
          shift: [0.5px,-0.5py]
        - ref: matrix_pinky_bottom
          shift: [-0.5px,-1.5py-1.5]
        - ref: matrix_pinky_home
          shift: [-0.5px,0]
        - ref: matrix_inner_home
          shift: [0.5px,0] 
      fillet: 0.8
  keys:
    - what: rectangle
      where: true
      bound: false
      size: [14, 14]
  case_outline:
    - name: case_raw
    - operation: add
      name: case_compensation
  outline:
    - name: raw
    - operation: add
      name: compensation
  plate:
    - name: raw 
    - operation: subtract
      name: keys
cases:
  bottom:
    - name: case_outline
  plate:
    - name: plate
      extrude: 1.2
pcbs:
  board:
    template: kicad8
    outlines:
      main:
        outline: outline
    footprints: 
      keyswitches:
        where:  true
        what: ceoloide/switch_choc_v1_v2
        params:
          reversible: true 
          include_keycap: true
          solder: false
          include_stabilizer_pad: false
          choc_v1_support: false
          from: "{{column_net}}"
          to: "{{colrow}}"
      diode:
        what: ceoloide/diode_tht_sod123 
        where: true
        params:
          include_traces_vias: true 
          reversible: true 
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0,-0.28ky]
      mcu:
        what: ceoloide/mcu_supermini_nrf52840
        params:
          reversible: true
        where:
          ref: matrix_index_thumb
          shift: [-48.5,-1.5]
          rotate: 90 
      reset:
        what: ceoloide/reset_switch_tht_top
        params:
          reversible: true
        where:
          ref: matrix_middle_bottom 
          shift: [4.5, -36]
      power: 
        what: ceoloide/power_switch_smd_side
        params:
          reversible: true
        where:
          ref: matrix_middle_bottom
          shift: [-6, -36]
          rotate: -90
      # wire_hole:
      #   what: ceoloide/mounting_hole_npth
      #   where:
      #     ref: matrix_middle_bottom 
      #     shift: [-4, -25]
      #   params:
      #     hole_size: 3 
      #     hole_drill: 3
      battery:
        what: ceoloide/battery_connector_molex_pico_ezmate_1x02
        params:
          reversible: true
        where:
          ref: matrix_middle_bottom
          shift: [5.5, -13]
          rotate: -90 
      keyboard_name:
        what: ceoloide/utility_text
        where:
          ref: matrix_middle_bottom
          shift: [-1.5, -27.5]
        params:
          reversible: true
          height: 5
          width: 2.5
          thickness: 0.4
          text: MITOS-V3
      JLC:
        what: ceoloide/utility_text
        where:
          ref: matrix_index_thumb
          shift: [0, -10]
        params:
          height: 1
          thickness: 0.15
          text: JLCJLCJLCJLC
      hole_lefttop:
        what: ceoloide/mounting_hole_npth
        where:
          ref: matrix_pinky_top
          shift: [0.5kx, -0.1ky]
        params:
          hole_size: 5
          hole_drill: 5
      hole_leftbottom:
        what: ceoloide/mounting_hole_npth
        where:
          ref: matrix_pinky_bottom
          shift: [0.5kx, -0.25ky]
        params:
          hole_size: 5
          hole_drill: 5
      hole_righttop:
        what: ceoloide/mounting_hole_npth
        where:
          ref: matrix_inner_top
          shift: [-0.5kx, -0.1ky]
        params:
          hole_size: 5
          hole_drill: 5
      hole_rightbottom:
        what: ceoloide/mounting_hole_npth
        where:
          ref: matrix_inner_thumb
          shift: [-0.5kx, -0.15ky]
        params:
          hole_size: 5
          hole_drill: 5
