units:
  # Proxy Spacing Variables
  kx: cx
  ky: cy
  # Padding Variables
  px: cx + 4
  py: cy + 4
  $default_width: cx
  $default_height: cy
points:
  zones:
    matrix:
      anchor:
        shift: [175,-175]
      key:
        padding: 1ky
        spread: 1kx
      columns:
        pinky:
          rows.thumb.skip: true
          key:
            stagger: 0
            column_net: P006
        ring:
          rows.thumb.skip: true
          key:
            stagger: 5
            column_net: P008
        middle:
          rows.thumb.skip: true
          key:
            stagger: 3
            column_net: P017
        index:
          key:
            stagger: -8
            column_net: P020
        inner:
          key:
            stagger: -2
            column_net: P022
      rows:
        thumb:
          row_net: P024
        bottom:
          row_net: P100
        home:
          row_net: P011
        top:
          row_net: P104
outlines:
  raw:
    - what: rectangle
      where: true
      size: [px,py]
      fillet: 0.8
  board:
    - what: polygon
      operation: stack
      points:
        - ref: matrix_inner_thumb
          shift: [0.5px,-0.5py]
        - ref: matrix_pinky_bottom
          shift: [-0.5px,-0.5py-kx-1]
        - ref: matrix_pinky_home
          shift: [-0.5px,0]
        - ref: matrix_inner_home
          shift: [0.5px,0] 
      fillet: 0.8
  keys:
    - what: rectangle
      where: true
      bound: false
      size: [kx-0.5,ky-0.5]
  outline:
    - name: board
    - operation: add
      name: raw
  plate:
    - name: outline
    - operation: subtract
      name: keys
pcbs:
  board:
    outlines:
      main:
        outline: outline
    footprints: 
      keyswitches:
        where:  true
        what: choc
        params:
          hotswap: true
          reverse: true 
          keycaps: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      diode:
        what: diode
        where: true
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -5]
      mcu:
        what: mcu_nice_nano
        params:
          reversible: true
        where:
          ref: matrix_index_thumb
          shift: [-45,-1.5]
          rotate: 90 
