units:
  # Proxy Spacing Variables
  kx: 19 
  ky: 19
points:
  zones:
    matrix:
      anchor:
        shift: [175,-175]
      key:
        padding: 1ky
        spread: 1kx
      columns:
        pinky:
          rows.thumb.skip: true
          key:
            stagger: 0
            column_net: P2
        ring:
          rows.thumb.skip: true
          key:
            stagger: 5
            column_net: P3
        middle:
          rows.thumb.skip: true
          key:
            stagger: 3
            column_net: P4
        index:
          key:
            stagger: -8
            column_net: P5
        inner:
          key:
            stagger: -2
            column_net: P6
      rows:
        thumb:
          row_net: P10
        bottom:
          row_net: P16
        home:
          row_net: P14
        top:
          row_net: P15
outlines:
  raw:
    - what: rectangle
      where: true
      size: [kx,ky]
      fillet: 0.8
  board:
    - what: polygon
      operation: stack
      points:
        - ref: matrix_inner_thumb
          shift: [0.5kx,-0.5ky]
        - ref: matrix_pinky_bottom
          shift: [-0.5kx,-1.5ky-2]
        - ref: matrix_pinky_home
          shift: [-0.5kx,0]
        - ref: matrix_inner_home
          shift: [0.5kx,0] 
      fillet: 0.8
  keys:
    - what: rectangle
      where: true
      bound: false
      size: [14, 14]
  outline:
    - name: board
    - operation: add
      name: raw
  plate:
    - name: raw 
    - operation: subtract
      name: keys
cases:
  plate:
    - name: plate
      extrude: 1.2
pcbs:
  board:
    outlines:
      main:
        outline: outline
    footprints: 
      keyswitches:
        where:  true
        what: switch_gateron_ks27_ks33
        params:
          reversible: true 
          include_keycap: true
          solder: false
          from: "{{column_net}}"
          to: "{{colrow}}"
      diode:
        what: diode_tht_sod123 
        where: true
        params:
          include_tht: true
          reversible: true 
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0,0.3ky]
      mcu:
        what: mcu_nice_nano
        params:
          reversible: true
        where:
          ref: matrix_index_thumb
          shift: [-48.15,-0.75]
          rotate: 90 
      reset:
        what: reset_switch_tht_top
        params:
          reversible: true
        where:
          ref: matrix_middle_bottom 
          shift: [5, -35]
      power: 
        what: power_switch_smd_side
        params:
          reversible: true
        where:
          ref: matrix_middle_bottom
          shift: [-6, -35]
          rotate: -90
      battery:
        what: battery_connector_jst_ph_2
        params:
          reversible: true
        where:
          ref: matrix_middle_bottom
          shift: [5, -20]
      hole_lefttop:
        what: mounting_hole_plated
        where:
          ref: matrix_pinky_top
          shift: [0.5kx, 0.25ky]
      hole_leftbottom:
        what: mounting_hole_plated
        where:
          ref: matrix_pinky_bottom
          shift: [0.5kx, 0.25ky]
      hole_righttop:
        what: mounting_hole_plated
        where:
          ref: matrix_inner_top
          shift: [-0.5kx, 0.25ky]
      hole_rightbottom:
        what: mounting_hole_plated
        where:
          ref: matrix_inner_thumb
          shift: [-0.5kx, 0.15ky]
          
